### ISSUE TITLE
Coefficient explosion during MacLane approximation

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#15]
This is a problem with the mac_lane code in sage-8.2. In mclf it causes trouble when computing "upper components".
Let K be a number field, F = K(x) a rational function field and v a discrete valuation on F which restricts to  a p-adic valuation on K. Let G in F[y] be a monic v-integral polynomial over F. Computing the MacLane approximants of G with respect to v sometimes leads to an explosion of coefficients, resulting in unacceptable running time and memory demand. Here is an example: 

    from mclf import *
    R.<z> = QQ[]
    K.<pi3> = NumberField(z^3+6)
    vK = QQ.valuation(2).extension(K)
    F.<x> = FunctionField(K)
    X = BerkovichLine(F, vK)
    xi = X.point_from_discoid(x^4 + 16*x^2 + 32*x + 64, 20/3)
    v = xi.valuation()
    v

    S.<y> = F[]
    G = y^2 - 2*x^5 + 8*x^3 + 80*x^2 + 128*x + 192
    w0 = GaussValuation(S, v)
    w1 = w0.mac_lane_step(G)[0]
    w1

    w2 = w1.mac_lane_step(G)[0]
    w2 

The last output, w2, is of the form

    [ Gauss valuation induced by Valuation on rational function field induced by [ Gauss valuation
    induced by 2-adic valuation, v(x) = 3/2, v(x^2 + 8) = 13/4, v(x^4 + 16*x^2 + 32*x + 64) = 20/3 ], 
     v(y + ....) ]

where ... is a polynomial in x of degree 108, with gigantic rational coefficients.  The next MacLane step takes already too long.

A possible reason for this problem is that the function `element_with_valuation` has only a generic implementation for function field valuations. In the "modified" branch of my mac_lane fork I added a few lines which fixed a similar (or the same?) problem. See [here](https://github.com/swewers/mac_lane/commit/e31d9ff0fa628e341a2e9f2877e0dd6f1a7073c6). 

**TODO**:
* [x] ~~Review [#25397](https://trac.sagemath.org/ticket/25397)~~ (merged)
* [x] Review [#25607](https://trac.sagemath.org/ticket/25607)

**Comment by saraedum** [comment]
This is now https://trac.sagemath.org/ticket/25397.

**Comment by swewers** [comment]
I have just made a pull request which contains some experimental code which is supposed to be a preliminary fix for this issue. It would be much better to integrate things like this into the mac_lane code directly. 

It needs to be tested more and better made into a proper module before a merge.  

I am not sure how this cooperates with https://trac.sagemath.org/ticket/25397. Maybe my code becomes superfluous, but it may also be that the two changes strengthen each other.  

In the mac_lane code, there is a function `simplify` attached to valuations, which in principal should do something similar, but I couldn't make it do what I wanted  it to do.

**Comment by swewers** [comment]
In the example from the beginning,

    from mclf import *
    R.<z> = QQ[]
    K.<pi3> = NumberField(z^3+6)
    vK = QQ.valuation(2).extension(K)
    F.<x> = FunctionField(K)
    X = BerkovichLine(F, vK)
    xi = X.point_from_discoid(x^4 + 16*x^2 + 32*x + 64, 20/3)
    v = xi.valuation()
    v

    S.<y> = F[]
    G = y^2 - 2*x^5 + 8*x^3 + 80*x^2 + 128*x + 192

the new function computes the unique approximant in something like 90 seconds and gets a very nice representation:

    sage: mac_lane_approximants_experimental(v, G)
    [[ Gauss valuation induced by Valuation on rational function field induced by [ Gauss valuation 
    induced by 2-adic valuation, v(x) = 3/2, v(x^2 + 8) = 13/4, v(x^4 + 16*x^2 + 32*x + 64) = 20/3 ], 
    v(y + 4*x + 40) = 31/8 ]]

It should be much faster, but there is an intermediate mac_lane_step where the key polynomial becomes very complicated, and probably most of the time is spend there. If one could do these simplifications during the whole computation (and not just after each mac_lane_step) things may be even faster.

**Comment by saraedum** [comment]
With 25397, I get: `[[ Gauss valuation induced by Valuation on rational function field induced by [ Gauss valuation induced by 2-adic valuation, v(x) = 3/2, v(x^2 + 8) = 13/4, v(x^4 + 16*x^2 + 32*x + 64) = 20/3 ], v(y - 3/64*x^6 - 9/8*x^4 - 3/2*x^3 - 9*x^2 - 24*x - 16) = 31/8 ]]` which is not as good as yours :)

**Comment by saraedum** [comment]
Putting both together, I get
```
Wall time: 1.12 s
[[ Gauss valuation induced by Valuation on rational function field induced by [ Gauss valuation induced by 2-adic valuation, v(x) = 3/2, v(x^2 + 8) = 13/4, v(x^4 + 16*x^2 + 32*x + 64) = 20/3 ], v(y + 20*x + 8) = 31/8 ]]
```

**Comment by saraedum** [comment]
The existing `simplify` is supposed to do that and obviously it does a poor job at it. Let me try to find out what your approach is doing better and fix that upstream.

**Comment by saraedum** [comment]
With 25607 I am now at
```
[[ Gauss valuation induced by Valuation on rational function field induced by [ Gauss valuation induced by 2-adic valuation, v(x) = 3/2, v(x^2 + 8) = 13/4, v(x^4 + 16*x^2 + 32*x + 64) = 20/3 ], v(y + 4*x + 8) = 31/8 ]]
```
after 440ms.

**Comment by saraedum** [comment]
@swewers: Sorry for the noise, but this one is also pending review upstream :)

**Comment by swewers** [comment]
I have review 25607. Sorry for the long delay. I wasn't up to my best recently, and busy with other things.

**Comment by swewers** [comment]
https://trac.sagemath.org/ticket/25607 still needs work (7 pyflakes errors).

**Comment by saraedum** [comment]
True, I'll fix them right away.

**Comment by saraedum** [comment]
Hm…I fixed these in some other ticket that already has positive review...not sure which one exactly, but let's ignore them here as otherwise, I'll have to figure out the conflicts.

**Comment by saraedum** [comment]
Fixed upstream.
