### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#34]
After the last couple of commits, the example in the README file is now outdated. I will write a new example soon.

**Comment by saraedum** [comment]
Btw when you change the README, you also need to change `example.ipynb` accordingly.

**Comment by swewers** [comment]
Just created a pull request which provides the update.

**Comment by swewers** [comment]
Pull request merged. Two things are still amiss:
1. The binder test is not as it should be: one ipython cell can only have one line with output, it seems.
2. coverage test fails. I don't know what this means.

**Comment by saraedum** [comment]
2. Not sure what's the problem here. Somehow, the test failed to download something. I restarted the test. That should fix it.

**Comment by saraedum** [comment]
Hm…actually, it's not. But it's completely unrelated to your changes.

**Comment by saraedum** [comment]
I will fix this with the next beta of Sage. Should be out in a few days.

**Comment by saraedum** [comment]
@swewers when you wrote
```
The binder test is not as it should be: one ipython cell can only have one line with output, it seems.
```
Do you mean that it does not print the results that you would like to see? Jupyter only always prints the last statement of each cell. Should we split it then?

**Comment by swewers** [comment]
Yes, I was expecting the same behaviour as in CoCalc, where all statement in a cell are printed.

**Comment by saraedum** [comment]
Should be fixed now.
