### ISSUE TITLE
Error "all roots of f must either lie inside or outside the unit disk"

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#39]
This error occurs e.g. in the following example:

    sage: v_2 = QQ.valuation(2)
    sage: R.<x> = QQ[]
    sage: f =  x^5 - 5*x^4 + 3*x^3 - 3*x^2 + 4*x - 1
    sage: Y = SuperellipticCurve(f, 2)
    sage: Y2 = SemistableModel(Y, v_2)
    sage: Y2.is_semistable()

It is triggered by an internal call of the method `polynomial_divisor(f, m)` with a polynomial `f` which is irreducible and has both integral and non-integral roots (note that f is *not* the polynomial from the example above). For such a polynomial f, it is at the moment impossible to define with Sage  a `LimitValuation`  v on the function field K(x) with v(f) = Infinity (restricting to the discrete valuation vK on K). 

You can work around this error as follows: by a coordinate change x --> x/p (or with some higher power of p, if necessary) all roots of f  can be made integral. 

    sage: g = f(x/2)*2^5
    sage: Y = SuperellipticCurve(g,  2)
    sage: Y2 = SemistableModel(Y, v_2)
    sage: Y2.is_semistable()
    True

Of course, this is not a satisfactory state of affairs, but it is not obvious how to fix this once and for all. I see several possibilities: 

1. Generalize the McLane algorithm such that it applies to polynomials G in K[x] which are not necessarily monic and integral. This would mean that you consider the coefficient with the least value of the valuation vK as 'leading coefficient'. Implement this generalization into Sage. 
2. Implement discrete valuations on function field F = K(x) which are induced from another such valuation via an *arbitrary* K-automorphism of F (at the moment, only the automorphism x-->1/x is allowed). This would make it very easy to fix the error by an internal coordinate change that the user doesn't see. 
3. Do some dirty trick in mclf which the user doesn' see..

In a way, 1 would be the best option, but I don't see that this gets done very soon..
Option 2 may be easier to do, and would be a good thing to have anyway. 
Nevertheless I will try Option 3 within the next 2 weeks or so. 

**TODO**:
* [x] Review [#25441](https://trac.sagemath.org/ticket/25441)

**Comment by saraedum** [comment]
I agree. 1 sounds best though I am a little worried that it could make the code more complicated. 2. Sounds easy though it is somewhat error prone as you have to remember to always drag all the methods on the function field valuation through the automorphism. I guess, 3 is a hacky version of 2 somehow?

**Comment by saraedum** [comment]
2. is now https://trac.sagemath.org/ticket/25441.

**Comment by saraedum** [comment]
I tried this with this not too pretty code:
```diff
index dff4ed5..50e4bdd 100644
--- a/mclf/berkovich/berkovich_line.py
+++ b/mclf/berkovich/berkovich_line.py
@@ -479,30 +479,35 @@ class BerkovichLine(SageObject):
             print("f = ", f)
             print("NP = ", NP)
             print("slopes = ", NP.slopes(False))
-        assert slopes == [] or max(slopes) <= 0 or min(slopes) >0,\
-            "all roots of f must either lie inside or outside the unit disk"
-        is_in_unit_disk = (slopes == [] or max(slopes) <= 0)
+        outside_of_unit_disk = (slopes != [] and min(slopes) > 0)
 
-
-        # this is the part inside the unit disk
-        if is_in_unit_disk:
-            f = f.monic()
+        if outside_of_unit_disk:
+            # the part outside the unit disk
+            f = f.reverse().monic()
             if not v0.is_equivalence_unit(f):
                 V = vK.mac_lane_approximants(f, require_incomparability=True, required_precision=1)
-                V = [LimitValuation(v, f) for v in V if not v.is_gauss_valuation()]
+                V = [LimitValuation(v, f) for v in V]
+                V = [v for v in V if v(x) > 0]
                 V = [F.valuation(v) for v in V]
+                V = [F.valuation((v, F.hom([1/x]), F.hom([1/x]))) for v in V]
                 D = [(TypeIPointOnBerkovichLine(self, v), m) for v in V]
             else:
                 D = []
         else:
-            # the part outside the unit disk
-            f = f.reverse().monic()
+            # this is the part inside the unit disk (possibly after some scaling)
+            f = f.monic()
+            c = f.base_ring().one()
+            while True:
+                if v0(f)>=0:
+                    break
+                c *= vK.uniformizer()
+                f = f(f.parent().gen()/vK.uniformizer()) * vK.uniformizer()**f.degree()
             if not v0.is_equivalence_unit(f):
                 V = vK.mac_lane_approximants(f, require_incomparability=True, required_precision=1)
-                V = [LimitValuation(v, f) for v in V]
-                V = [v for v in V if v(x) > 0]
+                V = [LimitValuation(v, f) for v in V if not v.is_gauss_valuation()]
                 V = [F.valuation(v) for v in V]
-                V = [F.valuation((v, F.hom([1/x]), F.hom([1/x]))) for v in V]
+                if not c.is_one():
+                    V = [F.valuation((v, F.hom([x/c]), F.hom([x*c]))) for v in V]
                 D = [(TypeIPointOnBerkovichLine(self, v), m) for v in V]
             else:
                 D = []
```
Maybe I should swap `x/c` and `x*c` but anyway, it then fails later, probably because this snippet in `berkovich_line` does not do the right thing anymore:
```python
        if v(x) >= 0:
            self._is_in_unit_disk = True
            self._v1 = v._base_valuation
        else:
            self._is_in_unit_disk = False
            self._v1 = v._base_valuation._base_valuation
```

**Comment by swewers** [comment]
> I tried this with this not too pretty code:

So this anticipates (https://trac.sagemath.org/ticket/25441) ? Can you "monkey patch" this change? otherwise we can't use this before Sage 8.3 becomes available..

My idea was to write a subclass of TypeIPointOnBerkovichLine which internally makes a coordinate change to represent a point by a valuation "up to coordinate change". All methods of this point would work as usual, except that xi.valuation() would be disabled (but xi.v(f) would work).

**Comment by swewers** [comment]
I have looked at my code again. I now belief that  https://trac.sagemath.org/ticket/25441 alone doesn't fix the issue (you mentioned a first problem above). The problem is that the class `TypeIPointOnBerkovichLine` does not really use the discrete valuation v on the function field K(x) that much, because the most import methods are not implemented yet (or were not implemented at the time the code was written) for such valuations. Very often I have/had to use v._base_valuation (the valuation on the polynomial ring v is induced from). 

It seems to me that it is necessary to rewrite most of `TypeIPointOnBerkovichLine` in such a way that 
the point xi is realized by a discrete valuation v0 on a polynomial subring K[y] of K(x), where we allow to be equal to p^n*x or 1/x (or even any 'parameter' with K(x)=K(y) ). This being done, it would be nice to be able to define the valuation v on K(x) extending v0, but it could also be easily avoided (a far as I can see). 

I may have time to do this the coming weekend (or earlier).

**Comment by swewers** [comment]
Ok, I'll test the new feature, but I also still think that it is necessary to work with the underlying valuation on the polynomial ring, at least within `berkovich_lines`, where the *discoid representation* of valuations are very important.

**Comment by swewers** [comment]
With the new monkey patch I receive, when running

    from mclf import *

the error message "mclf/monkey/util.py:86: UserWarning: Your installation of Sage has a known issue: https://trac.sagemath.org/ticket/25294. Please install patchy with `sage -pip install patchy` to fix this problem." When I try 

    sage -pip install patchy

I get "pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available."

**Comment by saraedum** [comment]
There are two possible reasons for this:
1) You don't have openssl installed. If you are on Ubuntu, `sudo apt install openssl` and try running the command again.
2) You did not have libssl-dev installed when you built Sage. `sudo apt install libssl-dev` and `sage -f python`. If you're lucky Sage is going to work after this normally. If not you have to rebuild Sage.

**Comment by swewers** [comment]
openssl ist installed, but libssl-dev not, and it doesn't seem to be available for openSuse in any repository.

**Comment by swewers** [comment]
And `sage -f python` fails with error message 

    make[1]: Entering directory '/home/stefan/comp/sage/sage-8.2/build/make'
    make[1]: *** No rule to make target 'python-clean'.  Schluss.
    make[1]: Leaving directory '/home/stefan/comp/sage/sage-8.2/build/make'

**Comment by saraedum** [comment]
`libssl-dev` is called `openssl-devel` in SUSE apparently.

**Comment by saraedum** [comment]
Sorry, `sage -f python2`.

**Comment by swewers** [comment]
Thanks, this works!

**Comment by saraedum** [comment]
@swewers: Do you think you could review the upstream issue so we get this into 8.4?

**Comment by swewers** [comment]
Done.

**Comment by saraedum** [comment]
Is in 8.3.
