### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#40]
This error is raised as follows:

    sage: v_2 = QQ.valuation(2)
    sage: R.<x> = QQ[]
    sage: f =  x^3 + 3
    sage: Y = SuperellipticCurve(f, 2)
    sage: Y2 = SemistableModel(Y, v_2)
    sage: Y2.is_semistable()

More precisely, it can be triggered by a call of `mac_lane_step` as follows:

    sage: R.<x> = QQ[]
    sage: K.<pi> = NumberField(x^6 + 126*x^3 + 126)
    sage: vK = QQ.valuation(2).extension(K)
    sage: R.<x> = K[]
    sage: v = GaussValuation(R, vK).augmentation(x, 2/3)
    sage: F.<x> = FunctionField(K)
    sage: v = F.valuation(v)
    sage: S.<y> = F[]
    sage: w0 = GaussValuation(S, v)
    sage: G = y^2 - x^3 - 3
    sage: w1 = w0.mac_lane_step(G)[0]
    sage: w1.mac_lane_step(G)

**Comment by saraedum** [comment]
Seems to be an issue in Sage's fraction field code.

**Comment by saraedum** [comment]
This is now https://trac.sagemath.org/ticket/25440.

**Comment by saraedum** [comment]
We can not monkey patch this btw.
