### ISSUE TITLE
TypeError: Cannot convert sage.rings.finite_rings.integer_mod.IntegerMod_int64 to sage.rings.finite_rings.integer_mod.IntegerMod_int

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#44]
This error can occur when a smooth projective curve over a large finite field is created, via the function `random_point`. A direct way to trigger it is as follows:

    sage: k = GF(55667)
    sage: F.<x> = FunctionField(k)
    sage: F._ring(x)(x)

So it is clearly a bug in Sage. 

**TODO**:
* [x] Review [#25449](https://trac.sagemath.org/ticket/25449)

**Comment by saraedum** [comment]
@swewers: Is it worth to monkey patch this in MCLF?

**Comment by swewers** [comment]
This has very low priority. I think we can wait for Sage 8.3 here.

**Comment by saraedum** [comment]
I think we missed the Sage 8.3 window with this one. @swewers could you try to review the upstream change so we get this into 8.4?

**Comment by swewers** [comment]
Done.

**Comment by saraedum** [comment]
This is in 8.3 now.
