### ISSUE TITLE
doctests and installing mclf

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#72]
If I try to run doctests for mclf modules, via e.g.

> sage -t mclf/curves/smooth_projective_curves.py

I get 

>  ImportError: No module named mclf

Then I tried to install mclf via 

> sage -sh
> sage -python setup.py install

Then the doctesting worked, but I got funny files called ``mclf.egg-info`` and the like in the mclf directory.  So these files change the git repository, which is certainly not what one wants. My question:
- did I do something stupid by installing mclf?
- or is this how one should do it, which means that mclf.egg-info has to be listed in .gitignore?

**Comment by JRSijsling** [comment]
This can be undone, in the usual shell, via
```
sage -pip uninstall mclf
```
This may give you an error, but it does the job.

I think that this is how `setup.py` works by default. It makes these `build` and `dist` directories and sometimes lays an egg. You can indeed modify the `.gitignore` file, that will never cause problems anyway as long as only irrelevant files are mentioned. But an alternative command that can be used in the `mclf` directory is
```
sage -pip install .
```
a one-liner for which you need not to start up a SageMath shell, and which does not leave behind any mess at all, not even a `build` directory. It can be uninstalled similarly.

There are some small differences: this version does not install the .egg file but a directory with the source and some `egg-info` directory. This is what most installed packages in `sage/local/lib/python2.7/site-package` use.

**Comment by swewers** [comment]
Ok, they are in .gitignore. 

By the way, the command

> sage -pip install .

does something, but it does not solve the problem with doctesting. With 

> sage -sh
> sage -python setup.py install

everything is fine.

**Comment by saraedum** [comment]
I think that `sage setup.py install` should work as well. The `sage -sh` should not be necessary in that case.

**Comment by saraedum** [comment]
(at least I have `sage setup.py install && sage -tp henselization/` in my bash history so that seems to be the command that I use for testing.)
