### ISSUE TITLE
Docs fail to build

### ISSUE THREAD

**Issue by JRSijsling** [MCLF/mclf#84]
The following happens on my machine after installing `mclf` via either of the available methods and trying to compile the documentation. On Sage 8.3 I get an error of which the essential part is:
```
ImportError: cannot import name complex_number
Your installation of Sage has a known issue: https://trac.sagemath.org/ticket/25441. We tried to install a workaround for this problem but failed to do so. Please make sure that you are using the latest stable version of Sage. If you are using the latest stable version of Sage already, please report this issue at https://github.com/MCLF/mclf/issues including the traceback below.
```
Full traceback at https://gist.github.com/JRSijsling/19eb347c5e8a17b17c47f5ae4cbaa3fb.

**Comment by swewers** [comment]
I exactly have the same problem.

**Comment by saraedum** [comment]
How are you trying to build the documentation exactly?

**Comment by saraedum** [comment]
@JRSijsling @swewers : Does #86 fix your problem? For me `make html` works inside and outside of Sage now.

**Comment by swewers** [comment]
It works for me with
> import sage.all
