### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#85]
In README, the command to install should rather be 

> sage -pip install mclf --user --upgrade

or not?

**Comment by saraedum** [comment]
Is that different from
> sage -pip install --user --upgrade mclf
?

**Comment by saraedum** [comment]
I had added the `--upgrade` to the `README.md` already but it's not on PyPI yet. Is that the confusion here?

**Comment by swewers** [comment]
No, but I copy and pasted the command and forgot the mclf, because it was in the next line. 
Sorry..
