### ISSUE TITLE
Empty documentation

### ISSUE THREAD

**Issue by saraedum** [MCLF/mclf#93]
In some cases, the generated documentation is empty, see https://github.com/MCLF/mclf/pull/86#issuecomment-410606826.

**Comment by saraedum** [comment]
@JRSijsling I can not reproduce the issue you reported in https://github.com/MCLF/mclf/pull/86#issuecomment-410606826. For me that command yields proper HTML output. Could you share more details please?

**Comment by JRSijsling** [comment]
Actually it works now after I removed the old build directory! Apparently something was left there that messed up rebuilds. Not any more though. Consider this solved.
