### ISSUE TITLE
Unexplained error in mac_lane_step

### ISSUE THREAD

**Issue by swewers** [MCLF/mclf#94]
The following gives an error message:

> sage: from mclf import *
> sage: R.<x> = QQ[]
> sage: v_2 = QQ.valuation(2)
> sage: v = GaussValuation(R, v_2).augmentation(x+1, 1/2)
> sage: f = x^4 - 30*x^2 - 75
> sage: v.is_equivalence_unit(f)
> sage: v.mac_lane_step(f)
> False
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-134211954710> in <module>()
      5 f = x**Integer(4) - Integer(30)*x**Integer(2) - Integer(75)
      6 v.is_equivalence_unit(f)
----> 7 v.mac_lane_step(f)

/home/stefan/comp/SageMath/local/lib/python2.7/site-packages/sage/rings/valuation/inductive_valuation.pyc in mac_lane_step(self, G, principal_part_bound, assume_squarefree, assume_equivalence_irreducible, report_degree_bounds_and_caches, coefficients, valuations, check)
    843                     ret.append((w, degree_bound, multiplicities[slope], w_coefficients, new_valuations))
    844 
--> 845         assert ret
    846         if not report_degree_bounds_and_caches:
    847             ret = [v for v,_,_,_,_ in ret]

AssertionError: 
sage:

**Comment by swewers** [comment]
This would be good. The error occurs only very rarely (otherwise I would have found it already), but the option of using mac_lane_step starting from the "wrong value" is used a lot in mclf.

**Comment by swewers** [comment]
Thanks!

**Comment by swewers** [comment]
I wrote a positive review, but again, there seems to be a problem with the patchbot, unrelated with the ticket.

**Comment by saraedum** [comment]
This is now in the latest 8.4 beta.
